[[services]]
  internal_port = 5003
  protocol = "tcp"

[[services.ports]]
  handlers = ["http"]
  port = 80

[[services.tcp_checks]]
  grace_period = "10s"
  interval = "30s"
  restart_limit = 3
  timeout = "5s"
