# fly.toml app configuration file generated for chatbot-gpt-gw9p5q on 2025-02-16T16:24:46Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chatbot-gpt-gw9p5q'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 5003
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
